### ISSUE TITLE
Ошибки консоли

### ISSUE THREAD

**Issue by Destors** [SvtlnR/SvtlnR.github.io#2]
![image](https://user-images.githubusercontent.com/36758083/42441711-841188c6-8371-11e8-9cda-9b56848a862b.png)
-Исправь ошибки консоли.

/сс @soul-wish

**Comment by soul-wish** [comment]
@Destors и тут разберись в чем проблема, пожалуйста.

**Comment by SvtlnR** [comment]
Это из-за блокировщика вроде

**Comment by soul-wish** [comment]
Спасибо Света, все верно. @Destors найди, пожалуйста реальную проблему и заведи еще одно issue.

**Comment by soul-wish** [comment]
А это @SvtlnR закрывай.
