### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by ppashkov** [SvtlnR/SvtlnR.github.io#3]
Зафиксированный футер перекрывает текст на больших устройствах

![2018-07-09 12-39-41](https://user-images.githubusercontent.com/40775247/42443140-5a1d17d4-8375-11e8-98fa-7f995308b54b.png)
![2018-07-09 12-39-48](https://user-images.githubusercontent.com/40775247/42443141-5a41806a-8375-11e8-93a7-ff674c509c61.png)
/сс @soul-wish

**Comment by SvtlnR** [comment]
Задала фон футеру, чтоб текст не сливался.
