### ISSUE TITLE
nav

### ISSUE THREAD

**Issue by Destors** [SvtlnR/SvtlnR.github.io#6]
![image](https://user-images.githubusercontent.com/36758083/42475797-6f1eb958-83d4-11e8-8bac-fca8a5d5b100.png)
-nav помести в header.

**Comment by SvtlnR** [comment]
Поскольку <nav> необязательно должен быть в хедере, я не стала переделывать, так как на текущий момент была готова адаптивность. Но на будущее учту. Спасибо.
