### ISSUE TITLE
не работает ссылка на gmail.com

### ISSUE THREAD

**Issue by Sasha1345** [SvtlnR/SvtlnR.github.io#7]
/сс @soul-wish

**Comment by SvtlnR** [comment]
Жора сделал

**Comment by soul-wish** [comment]
@SvtlnR Жора может и сделал, но это же было твое решение влить неработающий код? Переоткрывай это issue – нужно фиксить. @Sasha1345 хорошо подметил.

**Comment by SvtlnR** [comment]
вроде переходит по ссылке и создает письмо новое мне при нажатии, я только когда обновляла добавила чтоб в новой странице открывало

**Comment by soul-wish** [comment]
@SvtlnR что делать тем миллионам людей, которые не пользуются GMail? Регистрироваться в Google для того что бы отправить письмо? И по поводу письма: вот у меня gmail есть, но письмо не создается ;)

**Comment by SvtlnR** [comment]
исправила
